name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14.x, 16.x, 18.x]

    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js 16.14.0
        uses: actions/setup-node@v3
        with: 
              node-version: ${{matrix.node-version}}

      - name: npm init
        run: npm init -y

      - name: Install Node.js dependencies
        run: npm install

      - name: Install React Native CLI
        run: npm install -g react-native-cli
    


